name: Deploy Web
on:
  push:
    branches:
      - gh-pages
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Copy Markdown Files
        run: |
          cp -f {README.md,cover_small.jpg} ./docs/
          cd docs
          npx vuepress build

      - name: Deploy Github
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ES6_DOCS_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
          publish_branch: master
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Deployed from bot > ${{ github.event.head_commit.message }}"
